# Generated by Django 5.2.5 on 2025-08-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userskill",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="userskill",
            name="is_available_for_freelance",
            field=models.BooleanField(default=False),
        ),
    ]
